### ISSUE TITLE
Allow for alternative title bar positions

### ISSUE THREAD

**Issue by marco-calautti** [paulmcauley/klassy#70] opened 2023-01-31 17:03 UTC
It would be great if the title bar could be moved on the side of the windows, rather than having it on the top.
Something similar to this:
![immagine](https://user-images.githubusercontent.com/8049741/215831636-8c8f237e-cab0-43c7-9880-97c70dbda3c0.png)

At the moment, this is only possible with aurorae theme, with some workarounds. Having it embedded in klassy would be very useful.

**Comment by paulmcauley** [comment] 2023-05-09 01:32
Duplicate of #48

**Closed by paulmcauley** 2023-05-09 01:32 UTC
Labels: duplicate
