### ISSUE TITLE
Wayland GTK apps do not utilize the Breeze GTK theme modifications that this project makes

### ISSUE THREAD

**Issue by d-avery** [paulmcauley/klassy#85] opened 2023-05-16 07:35 UTC
Steps to reproduce:
- Enable Klassy
- Enable Breeze GTK app style
- Start a GTK3 app in Wayland
- Close, Minimize and Maximize buttons look the same as in regular breeze

Expected result:
- Close, Minimize and Maximize buttons are modified by Klassy to look somewhat like the configured Qt buttons. (This works in X11, check attachments)

Environment: 
- EndeavourOS (6.3.1-arch1-1) 
- Plasma 5.27.5 Wayland

Check the following images for details:
Problematic Wayland GTK3 titlebar buttons:
![image](https://github.com/paulmcauley/klassy/assets/29543330/f66e25a9-91dd-4f95-a4ab-5e49e66c3dc1)

Functioning as intended X11 GTK3 titlebar buttons:
![image](https://github.com/paulmcauley/klassy/assets/29543330/c2cabd59-2b50-4ad0-ac02-e62718861f09)

**Comment by paulmcauley** [comment] 2023-05-16 13:12
Yes, this is a known limitation within Plasma Wayland caused by a decision by the GTK developers ( https://bugs.kde.org/show_bug.cgi?id=437082 ).

To workaround this, install a matching Klassy icon theme ( https://github.com/paulmcauley/klassy#system-icon-theme ) and then set the "GNOME/GTK Application Style" to "Adwaita".
![gtk_application_style](https://github.com/paulmcauley/klassy/assets/6924479/53c01b99-4411-40ea-9e21-6375d48fea48)

**Comment by paulmcauley** [comment] 2023-06-06 22:28
Closing as upstream

**Closed by paulmcauley** 2023-06-06 22:28 UTC
