### ISSUE TITLE
Blurred background in Konsole not working

### ISSUE THREAD

**Issue by SuNNjek** [paulmcauley/klassy#130] opened 2024-04-02 13:06 UTC
When enabling blurred and transparent window background in Konsole, the background doesn't get blurred. I assume this is an issue in Klassy because it works when I switch my global application theme back to Breeze.

With Klassy:
![Screenshot_20240402_150316](https://github.com/paulmcauley/klassy/assets/20151081/090a9ebf-6865-43f1-93ff-1816401a5752)

With Breeze:
![Screenshot_20240402_150352](https://github.com/paulmcauley/klassy/assets/20151081/40dbd147-82dd-443a-a6b5-846ad711380f)

**Comment by paulmcauley** [comment] 2024-04-02 16:00
It is not an issue in Klassy. Konsole does not set its blur region properly. Klassy does. 

Duplicate of #114

**Closed by paulmcauley** 2024-04-02 16:00 UTC
Labels: duplicate
