### ISSUE TITLE
Help with manually building and installing Plasma 6 git development version

### ISSUE THREAD

**Issue by mercifulboss** [paulmcauley/klassy#113] opened 2024-03-06 18:05 UTC
After updating to Plasma 6.0.1, it seems that 
1, The Klassy theme disappeared from my window themes menu
2. Prior to me manually switching back to breeze theme, the screen went black with only a cursor (the compositor crashed).

There might need to be some updates to Klassy. I will try to reinstall the theme

I recloned the repo and did `./install.sh` as per the instructions, I got an error building it:

![image](https://github.com/paulmcauley/klassy/assets/90151527/0c2a1aa4-b2e8-41ac-8937-810cc0b82edb)

**Comment by paulmcauley** [comment] 2024-03-06 18:50
That is the problem with manually installing from git, rather than waiting for a released packaged version.

First check that the old Plasma 5 version has uninstalled properly (it should have if you ran install.sh from the same directory you built from the first time. If not, try running ./uninstall.sh from the original directory). The following files should be deleted:
```
/usr/bin/klassy-settings
/usr/lib64/cmake/Klassy/KlassyConfig.cmake
/usr/lib64/cmake/Klassy/KlassyConfigVersion.cmake
/usr/lib64/libklassycommon5.so.4.3.breeze5.27.5 (filename corresponds to the version you installed)
/usr/lib64/libklassycommon5.so.5
/usr/lib64/qt5/plugins/org.kde.kdecoration2/klassydecoration.so
/usr/lib64/qt5/plugins/plasma/kcms/klassy/kcm_klassydecoration.so
/usr/lib64/qt5/plugins/plasma/kcms/systemsettings_qwidgets/klassystyleconfig.so
/usr/lib64/qt5/plugins/styles/klassy.so
/usr/share/applications/kcm_klassydecoration.desktop
/usr/share/applications/klassystyleconfig.desktop
/usr/share/icons/hicolor/scalable/apps/klassy-settings.svgz
/usr/share/kstyle/themes/klassy.themerc
```
(lib64 might be lib, depending on your distribution)

To install the Plasma 6 in-progress development version you will first need new Qt6/KF6 build dependencies installed. I have not compiled a list of these for yet, and would like help to do this for different distributions.
For OpenSUSE Tumbleweed Unstable I installed at least the following (there may be more as I ended up just installing all the KDE developer packages):
`sudo zypper in cmake kf6-extra-cmake-modules libQt5Core-devel qt6-core-devel libQt5Gui-devel qt6-gui-devel libQt5DBus-devel qt6-dbus-devel libqt5-qtx11extras-devel kdecoration6-devel kcoreaddons-devel kf6-kcoreaddons-devel kguiaddons-devel kf6-kguiaddons-devel kconfigwidgets-devel kf6-kconfigwidgets-devel kwindowsystem-devel kf6-kwindowsystem-devel ki18n-devel kf6-ki18n-devel kiconthemes-devel kf6-kiconthemes-devel kpackage-devel kf6-kpackage-devel libQt5QuickControls2-devel qt6-quickcontrols2-devel frameworkintegration-devel kf6-frameworkintegration-devel kcmutils-devel kf6-kcmutils-devel kirigami2-devel kf6-kirigami-devel qt6-svg-devel qt6-xml-devel`

Then in your cloned git directory, you first need to switch to the plasma6.0 branch:
`git checkout plasma6.0`

Then:
`install.sh`

**Comment by mercifulboss** [comment] 2024-03-07 02:53
I followed your instructions above (I had already deleted classy prior to this issue), so I switched to `git checkout` as per your instructions. Installed with `./install.sh`. It seemed to have compiled fine:

![image](https://github.com/paulmcauley/klassy/assets/90151527/275723af-e475-4594-9ae3-b16bf457c3ac)

I am on Archlinux. I have all of the dependencies installed for Qt6 and plasma6,

**Comment by paulmcauley** [comment] 2024-03-07 03:15
Please test new features such as Presets - did a list of presets load when you click "Presets..."? Do they save properly? Also, whether global themes work and load window decoration/application style/icons/colours, whether auto-generated icon themes generate, colour settings can change (including custom colours). Also any feedback on aesthetics and ideas for design tweaks welcome.

For the bottom rounded corners question see the discussion here: https://github.com/paulmcauley/klassy/discussions/112 . The easiest short answer is just to increase the border size in Window Decoration settings.

**Comment by mercifulboss** [comment] 2024-03-07 03:37
> Please test new features such as Presets - did a list of presets load when you click "Presets..."? Do they save properly? Also, whether global themes work and load window decoration/application style/icons/colours, whether auto-generated icon themes generate, colour settings can change (including custom colours). Also any feedback on aesthetics and ideas for design tweaks welcome.
> 
> For the bottom rounded corners question see the discussion here: #112 . The easiest short answer is just to increase the border size in Window Decoration settings.

I saw a list of presets:
![image](https://github.com/paulmcauley/klassy/assets/90151527/8ff9ff03-98cc-431f-a36b-5a1729cc609a)

Here's me testing the `Chroma` preset:
![image](https://github.com/paulmcauley/klassy/assets/90151527/8c9a3713-ff27-4ce9-aaca-2eaf9580ffde)

Here's me saving and loading form a preset I made called `Rounded corners`:
![image](https://github.com/paulmcauley/klassy/assets/90151527/9c2f3c3e-d152-4b68-a143-1ebf12a5d12b)

Here's me trying a global theme (going from dark to light):
![image](https://github.com/paulmcauley/klassy/assets/90151527/72fe82fc-8f84-4bd4-a5a1-b88b96c42919)

I tried the other global themes, they all work.

I am not sure what a "auto-generated icon theme" is, but the global icon themes switch correctly. And I am using a custom Icon theme and it works as well.

For aesthetics, perhaps a button could be implemented to make it easier to round buttom corners? 

Also unchecking "Round bottom corners when no window borders" seems to resolve the issue:

![Klassy bottom window corners](https://github.com/paulmcauley/klassy/assets/90151527/647dfd7e-e19d-47eb-aaf6-c3e3cace0a5a)

**Comment by paulmcauley** [comment] 2024-03-07 03:45
>I am not sure what a "auto-generated icon theme" is

There is now a "Klassy" icon theme that auto-generates when you change a window decoration setting. It only generates icons for the window buttons, and inherits Breeze icons by default - you can change what icons it inherits under "System Icon Generation..." button, but I think the text there might be confusing.

**Comment by paulmcauley** [comment] 2024-03-07 03:52
> maintains the breeze application style but follows the window transparency/translucency rules of the program in terms of plasma style (what I mean is it extends not just to the headers but to the entire window)?

I want to integrate such features in the future, but I think the Application Style needs added Presets and Application-Specific Overrides like Window Decorations have in order to make it practical for many different applications. I also think that transparent effects are better in moderation, as they can be impractical if overused, hence have not been a priority.

**Comment by mercifulboss** [comment] 2024-03-07 03:57
> > I am not sure what a "auto-generated icon theme" is
> 
> There is now a "Klassy" icon theme that auto-generates when you change a window decoration setting. It only generates icons for the window buttons, and inherits Breeze icons by default - you can change what icons it inherits under "System Icon Generation..." button, but I think the text there might be confusing.

Ah yes, I changed the icons it inherits to the `hey-classic` and `hey-classic-dark` theme. Not sure if it did anything, but in context and windows menus i see the correct icons.

>I want to integrate such features in the future, but I think the Application Style needs added Presets and Application-Specific Overrides (quite a bit of work to implement) like Window Decorations have in order to make it practical for many different applications. I also think that transparent effects are better in moderation, as they can be impractical if overused, hence have not been a priority.

Yes, I agree. Window decorations in excess can be a hinderance. 

Is there a way to have window titlebar text to change color? the text is white and I can't really see it when the window is on a white background? I wonder if it would be too difficult to implement a function that detects the background color (light or dark) and changes the titlebar text accordingly? If it is, I can deal with it, no big deal.

**Comment by paulmcauley** [comment] 2024-03-07 04:02
> Is there a way to have window titlebar text to change color? the text is white and I can't really see it when the window is on a white background? I wonder if it would be too difficult to implement a function that detects the background color (light or dark) and changes the titlebar text accordingly? If it is, I can deal with it, no big deal.

No, that is not hard to do (I already have functions that do this for the icons already). I didn't implement it though as you can change the titlebar colour in your system colour scheme (which should be designed properly) and thought it would be just adding settings for the same thing in two places.

**Comment by paulmcauley** [comment] 2024-03-07 04:09
> Is there a way to have window titlebar text to change color? the text is white and I can't really see it when the window is on a white background? I wonder if it would be too difficult to implement a function that detects the background color (light or dark) and changes the titlebar text accordingly? If it is, I can deal with it, no big deal.

I assume you are talking about when using a translucent titlebar. Good idea. I think that might be possible using a composition mode such as QPainter::CompositionMode_Difference ( https://doc.qt.io/qt-6/qpainter.html#CompositionMode-enum ).

**Comment by mercifulboss** [comment] 2024-03-07 04:25
> > Is there a way to have window titlebar text to change color? the text is white and I can't really see it when the window is on a white background? I wonder if it would be too difficult to implement a function that detects the background color (light or dark) and changes the titlebar text accordingly? If it is, I can deal with it, no big deal.
> 
> I assume you are talking about when using a translucent titlebar. Good idea. I think that might be possible using a composition mode such as QPainter::CompositionMode_Difference ( https://doc.qt.io/qt-6/qpainter.html#CompositionMode-enum ).

Yes that's exactly it. I was experimenting with a translucent titlebar on a white background and it was hard to see. Would be a great feature!

Let me know if there is anything else that needs to be tested

**Comment by mercifulboss** [comment] 2024-03-07 04:57
> I also think that transparent effects are better in moderation

Truth be told, the only reason I wanted the Klassy rules for translucency to be a kvantum theme/plasma style was so that I could use it for the dock. I haven't found anything comparable yet to Klassy in terms of customization options.

**Comment by netizen-ais** [comment] 2024-03-07 07:46
> > I am not sure what a "auto-generated icon theme" is
> 
> There is now a "Klassy" icon theme that auto-generates when you change a window decoration setting. It only generates icons for the window buttons, and inherits Breeze icons for everything else by default - you can change what icons it inherits under "System Icon Generation..." button, but I think the text there might be confusing.

I think so. I didn't understand at first, and even after tests I was confused. Got me a while to experiment and get it

**Comment by mercifulboss** [comment] 2024-03-07 14:16
> > > I am not sure what a "auto-generated icon theme" is
> > 
> > 
> > There is now a "Klassy" icon theme that auto-generates when you change a window decoration setting. It only generates icons for the window buttons, and inherits Breeze icons for everything else by default - you can change what icons it inherits under "System Icon Generation..." button, but I think the text there might be confusing.
> 
> I think so. I didn't understand at first, and even after tests I was confused. Got me a while to experiment and get it

For me it shows the latest icon theme that i used

**Comment by paulmcauley** [comment] 2024-03-07 19:04
> > > > I am not sure what a "auto-generated icon theme" is
> > > 
> > > 
> > > There is now a "Klassy" icon theme that auto-generates when you change a window decoration setting. It only generates icons for the window buttons, and inherits Breeze icons for everything else by default - you can change what icons it inherits under "System Icon Generation..." button, but I think the text there might be confusing.
> > 
> > 
> > I think so. I didn't understand at first, and even after tests I was confused. Got me a while to experiment and get it
> 
> For me it shows the latest icon theme that i used
> 
> Edit:
> 
> Compare ![image](https://private-user-images.githubusercontent.com/90151527/310962772-2cd92b65-386e-4eb0-b533-989fb45b87ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzgyNzIsIm5iZiI6MTcwOTgzNzk3MiwicGF0aCI6Ii85MDE1MTUyNy8zMTA5NjI3NzItMmNkOTJiNjUtMzg2ZS00ZWIwLWI1MzMtOTg5ZmI0NWI4N2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZTdjOWM1Yjg1ZjU2Y2E4M2IzN2RhYjllZjdmOTFkOWQ5NGYyZmQyNTBlNDFjM2U2OTgwY2I2MGUyNTk2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KzZ65YUm8IyjQ6BwY_znHPE_UQ7s-N0lsjzy03xQozk)
> 
> Is it supposed to look like that?

If you have set "Hey-classic-dark" as one of the inherit options under "System Icon Genration..." then yes, it is. This is because Klassy only generates icons only for the window control buttons. You can't make the KDE icon preview show the different window control icons, but you can see the difference if you right-click on an open program in the panel for example, or look at the window control icons of some GTK apps.

**Comment by mercifulboss** [comment] 2024-03-08 05:16
> > > > > I am not sure what a "auto-generated icon theme" is
> > > > 
> > > > 
> > > > There is now a "Klassy" icon theme that auto-generates when you change a window decoration setting. It only generates icons for the window buttons, and inherits Breeze icons for everything else by default - you can change what icons it inherits under "System Icon Generation..." button, but I think the text there might be confusing.
> > > 
> > > 
> > > I think so. I didn't understand at first, and even after tests I was confused. Got me a while to experiment and get it
> > 
> > 
> > For me it shows the latest icon theme that i used
> > Edit:
> > Compare ![image](https://private-user-images.githubusercontent.com/90151527/310962772-2cd92b65-386e-4eb0-b533-989fb45b87ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MzgyNzIsIm5iZiI6MTcwOTgzNzk3MiwicGF0aCI6Ii85MDE1MTUyNy8zMTA5NjI3NzItMmNkOTJiNjUtMzg2ZS00ZWIwLWI1MzMtOTg5ZmI0NWI4N2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE4NTkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZTdjOWM1Yjg1ZjU2Y2E4M2IzN2RhYjllZjdmOTFkOWQ5NGYyZmQyNTBlNDFjM2U2OTgwY2I2MGUyNTk2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KzZ65YUm8IyjQ6BwY_znHPE_UQ7s-N0lsjzy03xQozk)
> > Is it supposed to look like that?
> 
> If you have set "Hey-classic-dark" as one of the inherit options under "System Icon Generation..." then yes, it is. This is because Klassy only generates icons for the window control buttons. You can't make the KDE icon preview show the different window control icons, but you can see the difference if you right-click on an open program in the panel for example, or look at the window control icons of some GTK apps.

Ah I see. Makes sense. When I went to delete the theme it now just shows "regular" klassy that is inheriting breeze theme:

![image](https://github.com/paulmcauley/klassy/assets/90151527/89390a5f-804f-4e65-aaff-8a6d1df00635)

**Comment by mercifulboss** [comment] 2024-03-08 20:26
I tested application themes with klassy, everything seems to work fine:

![image](https://github.com/paulmcauley/klassy/assets/90151527/07718aad-515b-4159-84b2-12b01fe764f5)

It looks really nice. 

It would be nice to also have the klassy theme make the side panel on dolphin transparent as well. I dont know if that's difficult to do, if it is no big deal. dolphin looks nice as is too.

**Comment by paulmcauley** [comment] 2024-03-08 20:32
> One thing I noticed is that the window titlebar text doesn't seem to match font color. Not sure if that's a icon issue and how to fix it.

I'm not sure what you mean, but if you mean that "titlebar text" under button colours isn't the same as the actual titlebar text, then click on "Button Colours..." and set "When poor contrast detected" to "Do nothing" or adjust the threshold value down.

**Comment by mercifulboss** [comment] 2024-03-08 20:40
Oh sorry I should have clarified

I was referring to the test on the titlebar that says `Home - Dolphin` not being the same color as everything else. It's not a big deal, was just a thought thats all :)

**Comment by paulmcauley** [comment] 2024-03-08 20:41
> Oh sorry I should have clarified
> 
> I was referring to the test on the titlebar that says `Home - Dolphin` not being the same color as everything else. It's not a big deal, was just a thought thats all :)

That is your system colour scheme

**Comment by mercifulboss** [comment] 2024-03-08 20:56
I discoevered that when is checked:

![image](https://github.com/paulmcauley/klassy/assets/90151527/e9c90e20-c145-4503-84d6-6abec4fb2a00)

It only works for the Breeze or Breeze Dark color scheme. Any other scheme just shows a transparent/blurred titlebar. I know it says "Experimental" but I thought I'd let you know

**Comment by paulmcauley** [comment] 2024-03-08 20:58
> I discoevered that when is checked:
> 
> ![image](https://private-user-images.githubusercontent.com/90151527/311364492-e9c90e20-c145-4503-84d6-6abec4fb2a00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5MzE3NDQsIm5iZiI6MTcwOTkzMTQ0NCwicGF0aCI6Ii85MDE1MTUyNy8zMTEzNjQ0OTItZTljOTBlMjAtYzE0NS00NTAzLTg0ZDYtNmFiZWM0ZmIyYTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDIwNTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MDZiOWFmMzFlZGNhNDUyNTdiODEwMTUzN2U5YzM0ZjI4NTJkNWVhODg3YjRhNmY4YThlNzhmZThhMTdhMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7pn86jgT8nLAM-3lyp-TRVszXwaV_3VUmoniR2EDsIE)
> 
> It only works for the Breeze or Breeze Dark color scheme. Any other scheme just shows a transparent/blurred titlebar. I know it says "Experimental" but I thought I'd let you know

No, it is as designed - it only works if the colour scheme has "header" colours set.

**Comment by mercifulboss** [comment] 2024-03-08 20:59
Ah apologies. You are right, I checked with Layan color theme and it did seem to work.

**Comment by netizen-ais** [comment] 2024-03-11 09:13
> That is the problem with manually installing from git, rather than waiting for a released packaged version.

I was building/running from git without any problems but today:

`kdecoration/breezedecoration.cpp: In member function ‘void Breeze::Decoration::updateButtonsGeometry()’:
kdecoration/breezedecoration.cpp:912:67: error: ‘Spacer’ is not a member of ‘KDecoration2::DecorationButtonType’
912 |         if (button->type() == KDecoration2::DecorationButtonType::Spacer) {
|                                                                   ^~~~~~`

**Comment by paulmcauley** [comment] 2024-03-11 11:00
> > That is the problem with manually installing from git, rather than waiting for a released packaged version.
> 
> I was building/running from git without any problems but today:
> 
> `kdecoration/breezedecoration.cpp: In member function ‘void Breeze::Decoration::updateButtonsGeometry()’: kdecoration/breezedecoration.cpp:912:67: error: ‘Spacer’ is not a member of ‘KDecoration2::DecorationButtonType’ 912 | if (button->type() == KDecoration2::DecorationButtonType::Spacer) { | ^~~~~~`

Could you try again now? What Plasma version are you using?

I had added support for configuring the new spacer buttons (https://invent.kde.org/plasma/breeze/-/merge_requests/403) but it turns out that this is to be a Plasma 6.1 feature and was not merged in KDecoration for Plasma 6.0.

![spacer](https://github.com/paulmcauley/klassy/assets/6924479/58482e85-7e5a-4912-9668-0e11ebc0ecf4)

**Comment by netizen-ais** [comment] 2024-03-11 11:48
> Could you try again now? What Plasma version are you using?

Builds and works correctly (in Plasma 6.0.0, KDE Neon User Edition) now.

**Comment by paulmcauley** [comment] 2024-03-11 13:41
> > > I am on Archlinux. I have all of the dependencies installed for Qt6 and plasma6
> > 
> > 
> > Mind sharing?
> 
> I would if I knew how to find what they are. It is all the necessary Qt dependencies to build plasma 6.

For Arch try installing the following:
```
frameworkintegration
gcc-libs
glibc
kcmutils
kcolorscheme
kconfig
kcoreaddons
kdecoration
kguiaddons
ki18n
kiconthemes
kirigami
kwidgetsaddons
kwindowsystem
qt6-base
qt6-declarative
qt6-svg
xdg-utils 
          
extra-cmake-modules
kcmutils5
frameworkintegration5
kconfigwidgets5
kiconthemes5
kirigami2
kwindowsystem5
```

**Comment by matterhorn103** [comment] 2024-03-13 00:04
Hi, I'm guessing there's a bit to do still before the first release for Plasma 6, and that after that it'll take a little time to work its way into the stable Tumbleweed releases. Which is fine, I appreciate the work you've done making Klassy a lot, there's no pressure here from me!

But assuming you won't have released by then – should I make sure to switch back to Breeze before I update to Plasma 6 on Tumbleweed (when it comes out)? To avoid:

> After updating to Plasma 6.0.1, it seems that
> 1, The Klassy theme disappeared from my window themes menu
> 2. Prior to me manually switching back to breeze theme, the screen went black with only a cursor (the compositor crashed).

Thanks for your efforts making the beautiful window decorations!

**Comment by matterhorn103** [comment] 2024-03-13 00:05
Oh, and once Plasma 6 releases on Tumbleweed, I'm more than happy to help test :)

**Comment by paulmcauley** [comment] 2024-03-13 00:10
> Hi, I'm guessing there's a bit to do still before the first release for Plasma 6, and that after that it'll take a little time to work its way into the stable Tumbleweed releases. Which is fine, I appreciate the work you've done making Klassy a lot, there's no pressure here from me!
> 
> But assuming you won't have released by then – should I make sure to switch back to Breeze before I update to Plasma 6 on Tumbleweed (when it comes out)? To avoid:
> 
> > After updating to Plasma 6.0.1, it seems that
> > 1, The Klassy theme disappeared from my window themes menu
> > 2. Prior to me manually switching back to breeze theme, the screen went black with only a cursor (the compositor crashed).
> 
> Thanks for your efforts making the beautiful window decorations!

If you installed Klassy from a the repository on the OpenSUSE Open Build Service then it should not matter, as the package manager should request to remove it.

I think though that I will have the Plasma 6 release out and packaged officially on OpenSUSE before it releases on Tumbleweed (maybe tomorrow), and if so it should be a smooth automatic transition.

**Comment by matterhorn103** [comment] 2024-03-13 09:05
Ok, that's amazing :)

I thought I had it from the main repo but no, it is from the OBS repo.

**Comment by paulmcauley** [comment] 2024-03-13 14:48
Debian/Ubuntu/Neon dependencies:
`sudo apt install build-essential cmake kf6-extra-cmake-modules kf6-extra-cmake-modules kf6-frameworkintegration-dev kf6-kcmutils-dev kf6-kcolorscheme-dev kf6-kconfig-dev kf6-kconfigwidgets-dev kf6-kcoreaddons-dev kf6-kguiaddons-dev kf6-ki18n-dev kf6-kiconthemes-dev kf6-kirigami2-dev kf6-kpackage-dev kf6-kservice-dev kf6-kwindowsystem-dev kirigami2-dev kwayland-dev libx11-dev libkdecorations2-dev libkf5config-dev libkf5configwidgets-dev libkf5coreaddons-dev libkf5guiaddons-dev libkf5i18n-dev libkf5iconthemes-dev libkf5kcmutils-dev libkf5package-dev libkf5service-dev libkf5style-dev libkf5wayland-dev libkf5windowsystem-dev libplasma-dev libqt5x11extras5-dev qt6-base-dev qt6-declarative-dev qtbase5-dev qtdeclarative5-dev gettext qt6-svg-dev`

**Comment by paulmcauley** [comment] 2024-03-13 16:39
Fedora dependencies:
sudo dnf install cmake extra-cmake-modules gettext

sudo dnf install "cmake(KF5Config)" "cmake(KF5CoreAddons)" "cmake(KF5FrameworkIntegration)"  "cmake(KF5GuiAddons)" "cmake(KF5Kirigami2)" "cmake(KF5WindowSystem)" "cmake(KF5I18n)" "cmake(Qt5DBus)" "cmake(Qt5Quick)" "cmake(Qt5Widgets)" "cmake(Qt5X11Extras)" "cmake(KDecoration2)" "cmake(KF6ColorScheme)" "cmake(KF6Config)" "cmake(KF6CoreAddons)" "cmake(KF6FrameworkIntegration)" "cmake(KF6GuiAddons)" "cmake(KF6I18n)" "cmake(KF6KCMUtils)" "cmake(KF6KirigamiPlatform)" "cmake(KF6WindowSystem)" "cmake(Qt6Core)" "cmake(Qt6DBus)" "cmake(Qt6Quick)" "cmake(Qt6Svg)" "cmake(Qt6Widgets)" "cmake(Qt6Xml)"

**Comment by paulmcauley** [comment] 2024-03-13 19:16
OpenSUSE dependencies:
```
sudo zypper in cmake kf6-extra-cmake-modules gettext

sudo zypper in "cmake(KF5Config)" "cmake(KF5CoreAddons)" "cmake(KF5FrameworkIntegration)"  "cmake(KF5GuiAddons)" "cmake(KF5Kirigami2)" "cmake(KF5WindowSystem)" "cmake(KF5I18n)" "cmake(KF5KCMUtils)" "cmake(Qt5DBus)" "cmake(Qt5Quick)" "cmake(Qt5Widgets)" "cmake(Qt5X11Extras)" "cmake(KDecoration2)" "cmake(KF6ColorScheme)" "cmake(KF6Config)" "cmake(KF6CoreAddons)" "cmake(KF6FrameworkIntegration)" "cmake(KF6GuiAddons)" "cmake(KF6I18n)" "cmake(KF6KCMUtils)" "cmake(KF6KirigamiPlatform)" "cmake(KF6WindowSystem)" "cmake(Qt6Core)" "cmake(Qt6DBus)" "cmake(Qt6Quick)" "cmake(Qt6Svg)" "cmake(Qt6Widgets)" "cmake(Qt6Xml)"
```

**Comment by paulmcauley** [comment] 2024-03-15 15:03
OK, closing this thread as the Plasma 6 version has now been released and I hopefully have made the installation instructions clearer:

Installation instructions for Plasma 6.0:

https://github.com/paulmcauley/klassy/tree/plasma6.0?tab=readme-ov-file#installation

Installation instructions for Plasma 5.27:

https://github.com/paulmcauley/klassy/tree/plasma5.27?tab=readme-ov-file#installation

**Closed by paulmcauley** 2024-03-15 15:03 UTC
