### ISSUE TITLE
Thin line under toolbar.

### ISSUE THREAD

**Issue by edpil02** [paulmcauley/klassy#91] opened 2023-06-03 08:40 UTC
Is there a way to disable the thin line under the toolbar.This line does not appear in breeze native and is annoying in certain color configurations.
Thanks.

![Screenshot_20230603_102759](https://github.com/paulmcauley/klassy/assets/43163048/c0422953-a1c7-4e48-96a3-004998273ba6)

**Comment by edpil02** [comment] 2023-06-05 11:20
Solved.

![Screenshot_20230605_131244](https://github.com/paulmcauley/klassy/assets/43163048/708850c0-bc32-4b7f-8eb3-d08019e2be4a)

@@ -1400,7 +1410,7 @@
     painter->drawRect(rect);

     painter->setPen(_helper->separatorColor(_toolsAreaManager->palette()));
-    painter->drawLine(rect.bottomLeft(), rect.bottomRight());
+   //  painter->drawLine(rect.bottomLeft(), rect.bottomRight());

**Comment by paulmcauley** [comment] 2023-06-06 00:31
Could you tell me which colour scheme this appears for, and whether that colour scheme has a header colour or not?

**Comment by paulmcauley** [comment] 2023-06-06 01:55
duplicate of #38

**Comment by edpil02** [comment] 2023-06-06 05:14
This issue append since i added a header color in my color sheme , which explain why the line i removed is in:
 
void Style::drawToolsAreaBackground(QPainter *painter, Helper *_helper, ToolsAreaManager *_toolsAreaManager, QMainWindow *mw, const QRect &rect)

**Comment by edpil02** [comment] 2023-06-06 05:42
I think the issue mentioned  in  https://github.com/paulmcauley/klassy/issues/38 is related to dolphin view 

![Screenshot_20230606_073038](https://github.com/paulmcauley/klassy/assets/43163048/bf025cff-f63c-4c80-9e1e-d20e95f0c8d5)

Thats why  im making a  lightly based  patch.

![Screenshot_20230606_073738](https://github.com/paulmcauley/klassy/assets/43163048/481c4461-43fa-45ec-8b01-d907ad8ef18e)

**Comment by paulmcauley** [comment] 2023-06-06 22:19
> Hi ! need help. I'm i don't know Qt nor programming , just a little code hacker and i'm stuck in my patch about transparency. Have you any idea how dolphinview transparency could be managed . I spent long hours to test some lightly piece of code related to , but no success. Thanks.

I will look at it some time in the future. I want it as a generic setting that can be applied to Dolphin via an Application-Specific override (a feature not implemented yet which will require some time)

**Closed by paulmcauley** 2023-06-06 22:19 UTC
Labels: duplicate
