### ISSUE TITLE
Close button has a white border when highlighted on an inactive window

### ISSUE THREAD

**Issue by slightlyfaulty** [paulmcauley/klassy#74] opened 2023-02-26 18:32 UTC
It seems no matter which settings I use, the close button always highlights with a white/light border when hovered over on an inactive window.

The only thing that seems to stop this from happening is if `Translucent backgrounds` is disabled.

![Klassy Close Border](https://user-images.githubusercontent.com/2036475/221429490-5f89c287-304d-4967-a45a-51d7d721904c.gif)

**Comment by paulmcauley** [comment] 2023-05-08 19:26
There is an auto-contrast detection algorithm. If it detects that there is not enough contrast between the button background and the titlebar/header colour then it will draw an outline around the button.

This works well most of the time but in some cases it doesn't. That's because it is a luma(greyscale)-based contrast detection algorithm from https://api.kde.org/frameworks/kguiaddons/html/namespaceKColorUtils.html#a9387fe7f2518a87367d9cbc82007994f and probably sees the greyscale values as similar. If you know of a better algorithm that can work in more cases then let me know.

**Comment by slightlyfaulty** [comment] 2023-05-08 23:18
Thanks for the explanation. I've played around with it a bit now and the grayscale contrast detection definitely doesn't work well in many cases. But that said, I understand why some form of contrast detection is necessary, and personally I can work around how it functions now, so it's not a big deal for me now that I know why it's happening.

Thanks again and keep up the great work. Klassy is awesome!

**Comment by paulmcauley** [comment] 2023-06-06 22:17
duplicate of #46

**Comment by paulmcauley** [comment] 2023-12-12 10:18
I may add a setting for the poor-contrast mitigation to be disabled

**Comment by paulmcauley** [comment] 2024-01-06 04:08
This now will no longer happen on master. The background colour is now adjusted in poor contrast situations instead of drawing an outline. It is now also confiurable.

**Closed by paulmcauley** 2024-01-06 04:08 UTC
Labels: duplicate
