### ISSUE TITLE
System icons recoloring issue

### ISSUE THREAD

**Issue by Dejweed** [paulmcauley/klassy#56] opened 2022-10-12 01:22 UTC
System icons aren't being recolored if they are white (most dark icon themes use white). When using light color scheme with dark icon theme buttons can become invisible (since it's white on white). 
I assume this is not an icon theme issue since it gets recolored just fine in GTK applications with Adwaita theme, but I did notice this issue isn't present with icons that use current color scheme as fill (like Breeze icon theme). However those icons don't change color when hovered.

![klassy_recolor](https://user-images.githubusercontent.com/65261588/195225542-9b632e28-95c4-4290-a6ab-732731831d27.png)
Notice the low visibility with Papirus-dark and Breeze

**Comment by Dejweed** [comment] 2023-12-09 01:34
Now they aren't getting recolored when hovered (see top right of the image in my previous comment: normally white, black when hovered). I'm also getting some pixels at top left of the button when using system icons:
![image](https://github.com/paulmcauley/klassy/assets/65261588/974d8f29-eb70-429f-a0eb-fefa29b1c7fe)

Also light on light close button with [JasperDark](https://github.com/vinceliuice/Jasper-kde) color scheme (**background colors: accent color**, always show icons and backgrounds, translucent backgrounds off):
![image](https://github.com/paulmcauley/klassy/assets/65261588/b874e5f1-4ff3-4a31-85a4-f486de58ff04)
Another example (almost same settings as last one, only difference **always show: icons**):
![image](https://github.com/paulmcauley/klassy/assets/65261588/37269268-08f6-4a10-85d7-bd84adc22b8e)

Unrelated to the colors, I would appreciate some UI "quality of life" improvements. When I was checking out different presets each time the preset gets loaded the window closes, so every time I had to reopen presets again. Some kind of apply/preview button would be nice. Same with general settings, you can't apply them without the window closing.
I feel like the new button customization (always show) could become difficult to navigate with drop down menus. Ticking checkboxes sounds easier to me, but I haven't tried it in practice yet. 
And since many settings focus on close button specifically, it could have it's own settings for those options (**always show** and **background colors**. Then there would also be an option for it to look just like other buttons (example libadwaita). Just an idea, I don't know how viable it would be codewise.

**Comment by paulmcauley** [comment] 2023-12-09 10:06
New commit 6c1e6c5e7dbe17c900ea9569b6d5f66595c3d3f9 should have fixed the glitches in the top-left (I hadn't even noticed these on a HiDPI screen!)

**Comment by Dejweed** [comment] 2023-12-09 14:23
Okay, with Jasper it might be the color scheme's issue, it also happens with menubars. But using Breeze Dark doesn't change colors as it used to. This also applies to non-system icons. Here's before and now:
![old⁄new](https://github.com/paulmcauley/klassy/assets/65261588/bd9a91db-25df-4e9b-8001-57d3c89f8f45)
I'm using slightly different settings but you get the idea.

**Comment by paulmcauley** [comment] 2023-12-09 15:01
> Okay, with Jasper it might be the color scheme's issue, it also happens with menubars. But using Breeze Dark doesn't change colors as it used to. This also applies to non-system icons. Here's before and now: ![old⁄new](https://private-user-images.githubusercontent.com/65261588/289276954-bd9a91db-25df-4e9b-8001-57d3c89f8f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzM3MjUsIm5iZiI6MTcwMjEzMzQyNSwicGF0aCI6Ii82NTI2MTU4OC8yODkyNzY5NTQtYmQ5YTkxZGItMjVkZi00ZTliLTgwMDEtNTdkM2M4OWY4ZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE0NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWFkMTFiZTNlZDJkZWI5ZmI2NmE1NmQzMzY0NTI2YzJkMjAxNzMwZTYwNjgzNGY5Njc5YjZkOThiMTEzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvArrdGpqBG1gUodIPDTk3dIh3I68Qe7jceesNd1884) I'm using slightly different settings but you get the idea.

There is a heuristic for contrast detection which might be what is causing this - it changes the icon to black/white if poor contrast. I am going to make this a toggle eventually.

> Now they aren't getting recolored when hovered (see top right of the image in my previous comment: normally white, black when hovered). I'm also getting some pixels at top left of the button when using system icons: ![image](https://private-user-images.githubusercontent.com/65261588/289211605-974d8f29-eb70-429f-a0eb-fefa29b1c7fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzM3MjUsIm5iZiI6MTcwMjEzMzQyNSwicGF0aCI6Ii82NTI2MTU4OC8yODkyMTE2MDUtOTc0ZDhmMjktZWI3MC00MjlmLWEwZWItZmVmYTI5YjFjN2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE0NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYTk2MmVkZWU3NGJhMDA4ZDk2YzBkOTQ4ZTkyODQzOTg0YjE0MDNjN2VlYTcxYzRhOThmMWFiMGEyZGNiMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ygs0bx0sjJBSdpBFputIFKVwfvKXbQ5D_MaoLBnEFVU)
This is a bug. I have it fixed on my local machine and will upload the fix later


> Also light on light close button with [JasperDark](https://github.com/vinceliuice/Jasper-kde) color scheme (**background colors: accent color**, always show icons and backgrounds, translucent backgrounds off): ![image](https://private-user-images.githubusercontent.com/65261588/289215361-b874e5f1-4ff3-4a31-85a4-f486de58ff04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzM3MjUsIm5iZiI6MTcwMjEzMzQyNSwicGF0aCI6Ii82NTI2MTU4OC8yODkyMTUzNjEtYjg3NGU1ZjEtNGZmMy00YTMxLTg1YTQtZjQ4NmRlNThmZjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE0NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MDc3Mzg0ZDBkMjY4YzIwYWE3M2MwZmZlODAxODViOGY0NWMwYmZiZmFlMTQ3ZTY5M2VmNGM1ODI1YjkxNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.okYAeKj24ddtTHEvaaGbJg-1phCobYqziMuf4QEZivM) Another example (almost same settings as last one, only difference **always show: icons**): ![image](https://private-user-images.githubusercontent.com/65261588/289216668-37269268-08f6-4a10-85d7-bd84adc22b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzM3MjUsIm5iZiI6MTcwMjEzMzQyNSwicGF0aCI6Ii82NTI2MTU4OC8yODkyMTY2NjgtMzcyNjkyNjgtMDhmNi00YTEwLTg1ZDctYmQ4NGFkYzIyYjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE0NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMDRjMWNmOTIzOTcxYzg2ZDQxMTI2MDJhYmViMjk4OTFjOGM3N2MxNDMxYzAyOTMyMTVmMmIyYWViZDZmOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W5HAccTuMDYpciPQnqc9ETb9cbjlo02yY0eQTgxQO8c)

These are just colours directly from the colour scheme. I am going to eventually add a custom colour configuration where you can override the colour-scheme and Klassy's hard-coded colours.
> 
> Unrelated to the colors, I would appreciate some UI "quality of life" improvements. When I was checking out different presets each time the preset gets loaded the window closes, so every time I had to reopen presets again. Some kind of apply/preview button would be nice. Same with general settings, you can't apply them without the window closing. I feel like the new button customization (always show) could become difficult to navigate with drop down menus. Ticking checkboxes sounds easier to me, but I haven't tried it in practice yet. And since many settings focus on close button specifically, it could have it's own settings for those options (**always show** and **background colors**. Then there would also be an option for it to look just like other buttons (example libadwaita). Just an idea, I don't know how viable it would be codewise.

Yes, a preset apply is a good idea. I can't add Apply to the main config in System Settings as that is provided by Plasma, so we need to file a bug there at http://bugs.kde.org . In the meantime you can run klassy-settings where there is an Apply button (/usr/bin/klassy-settings).

Yes, I think checkboxes would be easier too, but I am going to move all the Button Behaviour (Always Show/Highlight Using) options to a new window so will change it later. I also want behaviours and colours to be able to be set differently for active and inactive windows.

> But using Breeze Dark doesn't change colors as it used to. This also applies to non-system icons. Here's before and now: ![old⁄new](https://private-user-images.githubusercontent.com/65261588/289276954-bd9a91db-25df-4e9b-8001-57d3c89f8f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzM3MjUsIm5iZiI6MTcwMjEzMzQyNSwicGF0aCI6Ii82NTI2MTU4OC8yODkyNzY5NTQtYmQ5YTkxZGItMjVkZi00ZTliLTgwMDEtNTdkM2M4OWY4ZjQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE0NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWFkMTFiZTNlZDJkZWI5ZmI2NmE1NmQzMzY0NTI2YzJkMjAxNzMwZTYwNjgzNGY5Njc5YjZkOThiMTEzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zvArrdGpqBG1gUodIPDTk3dIh3I68Qe7jceesNd1884) I'm using slightly different settings but you get the idea.

I think this is the contrast heuristic again where it sets the icon colour to either black/white if there is poor contrast with the background.

**Comment by Dejweed** [comment] 2023-12-09 15:44
Awesome, I'm looking forward to these changes. Thank you for your work and for making such a great theme.

**Comment by paulmcauley** [comment] 2023-12-10 13:09
a412c70eba1c1c4eb4dfd107b09487b42a191029 should fix the colouring issues you mentioned. Let me know if any more problems

**Comment by paulmcauley** [comment] 2023-12-10 19:45
>Some kind of apply/preview button would be nice. Same with general settings, you can't apply them without the window closing. I feel like the new button customization (always show) could become difficult to navigate with drop down menus.

The Plasma bug/wishlist for this is at: https://bugs.kde.org/show_bug.cgi?id=463176 

Add your +1 there!

**Comment by Dejweed** [comment] 2023-12-10 23:12
Now it works as it should! But I think the translucent hovered accent color isn't opaque enough, and it gets inconsistent with the menubar colors (translucent backgrounds off, background color: accent color, always show icons):


https://github.com/paulmcauley/klassy/assets/65261588/f19a0c8b-354d-47ad-9e47-a3386a1f1ef2


Looking at the colorscheme (gruvbox in this case), it looks like menubar uses hover and focus colors, while titlebar icons both look like hover color, one more transparent, but neither match the window border color. Is this intentional?
![image](https://github.com/paulmcauley/klassy/assets/65261588/beeb6838-f7b0-4495-9782-1ee019dd50f7)



> Add your +1 there!

How do I do that? Do I just comment +1 like you did?

**Comment by paulmcauley** [comment] 2023-12-11 17:49
> But I think the translucent hovered accent color isn't opaque enough,
It was designed to match the Breeze "Blue Ocan" changes a couple of years ago. I may make there a slider for opacity.

 and it gets inconsistent with the menubar colors (translucent backgrounds off, background color: accent color, always show icons):
> hover.mp4
> 
> Looking at the colorscheme (gruvbox in this case), it looks like menubar uses hover and focus colors, while titlebar icons both look like hover color, one more transparent, but neither match the window's border color. On some other colorschemes it does match window's border color. Is this intentional? ![image](https://private-user-images.githubusercontent.com/65261588/289387847-beeb6838-f7b0-4495-9782-1ee019dd50f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTY2ODMsIm5iZiI6MTcwMjMxNjM4MywicGF0aCI6Ii82NTI2MTU4OC8yODkzODc4NDctYmVlYjY4MzgtZjdiMC00NDk1LTk3ODItMWVlMDE5ZGQ1MGY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE3Mzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZDNiM2Y4OGI5ZmJhNGVhNDVlYjk4NDBkYzc2YTBkZjVhZmZlODJhNDQxODIxMWYwMTRkZmI4ODNkMmY5ODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VHZfFcqWXrSpu3MjGkTz0zoprJRI6YoPFM1Tfc5kqKg)

Yes, that was a bug. They were the wrong way round. Fixed in 1b0a9fdf2116aee2ce4011487f83bdaf5a3df0f7 I also rewrote the entire code that selects the colour for the icon so that animations work properly, so let me know if you spot anything else!

The button accent colours are based off the "Button" group Hover and Focus. I was not sure whether the "Window" or "Button" group is more correct. The window outline accent is from QPalette::Highlight which is the same used in the titlebar separator from the original Breeze - it gives a slight more intense colour.
> > Add your +1 there!
> 
> How do I do that? Do I just comment +1 like you did?

Whatever you feel appropriate!
> 
> I found another example where the recoloring could be better: background: titlebar text color, always show icons and backgrounds, translucent off ![image](https://private-user-images.githubusercontent.com/65261588/289396430-bca0fe57-944a-4bdf-80f5-92d84318ed75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTY2ODMsIm5iZiI6MTcwMjMxNjM4MywicGF0aCI6Ii82NTI2MTU4OC8yODkzOTY0MzAtYmNhMGZlNTctOTQ0YS00YmRmLTgwZjUtOTJkODQzMThlZDc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE3Mzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MDY5ZjUwZmMxNzM2Nzg5YWY0ZTBiNWJhYmFiNDY4ZWIyZTE5ODU3YzVkZmM4NTY2NjgyMmUxNGYwYzU4MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PK-AJfU6YtI8n6EQ3AlQ30rsC6CS1LluHfE9CXhSV7c)

I have now changed this to be a mix between the titlebar and font colours.

> Unrelated to colors I also noticed outlines on square buttons look blurry (not 1 pixel wide).

This is fixed in 58e6bd06eb966d06077714c62053f67aeb86580e

**Comment by Dejweed** [comment] 2023-12-13 12:30
Utterly nord dark (background: accent colors, always show icons, translucent off): 
![image](https://github.com/paulmcauley/klassy/assets/65261588/868c6f42-84f0-4667-9c5c-0db67249758d)
I think black would be better when hovered.

Nice work with presets UI! 

Also unrelated to colors: When using certain color scheme (like Breeze light), using custom accent color (in KDE settings) draws outlines when there should only be background. 
My klassy-settings window size is too small by default. I'm also missing the icon for "Use system icon theme".
![image](https://github.com/paulmcauley/klassy/assets/65261588/876e52de-b969-4e9c-8ccd-d9559d08ed1a)

**Comment by Dejweed** [comment] 2023-12-13 13:25
> A black background? I think the background colour here is just taken from the colour scheme.

No no, the icon would be black.

> What icon theme are you using? It might not have included an icon for that.

Win98SE. Oh okay, it was the icon theme's issue. The icon used to be there so I thought it was related to klassy.

Are there plans to use system icons for shade and other buttons? From what is see, not every icon theme has them so that could be an issue, but those that do would look more coherent. 
And different colors for remaining traffic light buttons (shade, keep above/below...)?

**Comment by paulmcauley** [comment] 2023-12-13 13:33
> > A black background? I think the background colour here is just taken from the colour scheme.
> 
> No no, the icon would be black.

The icon colour is just from the colour scheme here. The contrast threshold I have set thinks its OK and I don't want to mess with it. There is going to be the option to override all button colours.

> 
> > What icon theme are you using? It might not have included an icon for that.
> 
> Win98SE. Oh okay, it was the icon theme's issue. The icon used to be there so I thought it was related to klassy.

OK, there was a code change on that icon. I will change it back and see if there is a fallback icon can be put there from Breeze.
> 
> Are there plans to use system icons for shade and other buttons? From what is see, not every icon theme has them so that could be an issue, but those that do would look more coherent.

If I can find a way to detect whether a system icon theme has an icon or not I would implement it differently. Have you found any icon themes with shade? (Keep above and below already use the system icon theme)

>  And different colors for remaining traffic light buttons (shade, keep above/below...)?

I want to make colours overridable for each button type.

**Comment by Dejweed** [comment] 2023-12-13 14:19
> Have you found any icon themes with shade? (Keep above and below already use the system icon theme)

Looking at Papirus, I found two icons, window-shade and xfce-wm-shade. Also window-pin and xfce-wm-stick. These are most common, but I feel like they are split between GTK/QT, so no single standard icon. If we take a look at breeze, it has window-shade/window-unshade and window-pin/window-unpin. Window-unpin is different, I couldn't find an icon that resembles PinnedOnAllDesktops. So yeah, I don't know if it's worth it.

**Comment by paulmcauley** [comment] 2023-12-13 16:55
I see there is a function:
 bool QIcon::hasThemeIcon(const QString &name)

I can maybe do a more intelligent icon lookup than at present

**Comment by paulmcauley** [comment] 2023-12-15 19:47
> Are there plans to use system icons for shade and other buttons? From what is see, not every icon theme has them so that could be an issue, but those that do would look more coherent. 

ebd6f878cf32d5e11d5ee9804f8f60d30f2e166c now allows all button types to use the system icon theme. Papirus now looks like this (though I'm not sure this is a good idea for all icon themes):
![Screenshot_20231215_193342](https://github.com/paulmcauley/klassy/assets/6924479/8bf581d8-5fd1-4b39-9928-a3ab83c437cd)

**Comment by paulmcauley** [comment] 2024-01-06 04:12
Master now has many more colour configuration options (with more coming). These should address all outstanding issues

**Closed by paulmcauley** 2024-01-06 04:12 UTC
